### ISSUE TITLE
Doublon de recette possible

### ISSUE THREAD

**Issue by MarieRoseLejay** [MarieRoseLejay/NESTI#11]
Dans la partie Administrateur il est possible de créer deux fois la même recette

**Comment by MarieRoseLejay** [comment]
Ajout d'une contrainte dans la base pour la table recette sur le titre et le résumé.

**Comment by Eva430** [comment]
Dear Frends, so mutch vor tke Help. I am rigtht on the.

**Comment by Eva430** [comment]
How itativcation?
